name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.25
  - scipy=1.11
  - cython=0.29
  - graph-tool=2.56
  - h5py=3.9
  - imageio=2.31
  - networkx=3.1
  - pip=23.1
  - pip:
    - evalutils==0.4
    - kimimaro==3.3
    - git+https://github.com/donglaiw/funlib.evaluate@5f08b1f088f246eef0336977d520ddc738bf8527
